[package]
name = "wasm2spirv-core"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
name = "wasm2spirv"
path = "src/cli.rs"
required-features = ["clap", "color-eyre", "serde_json"]

[dependencies]
bitflags = "2.3.3"
clap = { version = "4.3.16", optional = true, features = ["derive", "env"] }
color-eyre = { version = "0.6.2", optional = true }
itertools = "0.11.0"
once_cell = "1.18.0"
rspirv = "0.11.0"
serde = { version = "1.0.171", features = ["derive"] }
serde_json = { version = "1.0.103", optional = true }
spirv = { version = "0.2.0", features = ["serde", "serialize", "deserialize"] }
thiserror = "1.0.43"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
vector_mapp = "0.3.2"
wasmparser = "0.108.0"
wat = "1.0.67"

[dev-dependencies]
color-eyre = "0.6.2"
serde_json = "1.0.103"
