[package]
name = "wasm2spirv-c"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm2spirv = { version = "0.1.1", path = "../.." }
