[package]
name = "wasm2spirv-c"
edition.workspace = true
version.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spirv = "0.2.0"
wasm2spirv = { version = "0.1.1", path = "../.." }
