CC := "clang"
DIR := justfile_directory()
WORKSPACE := DIR / "../.."

build:
    cargo build --release

test: build
    {{CC}} {{DIR}}/tests/saxpy.c --std=c11 -I{{DIR}}/include -L{{WORKSPACE}}/target/release/ -lwasm2spirv_c -o {{DIR}}/tests/saxpy -lc -lstdc++ -lm -static
    {{DIR}}/tests/saxpy

test-wasm:
    cargo build --release --target wasm32-wasi --no-default-features --features="spvc"
