name: Release

on:
  release:
    types: [published]

jobs:
  build-cli:
    strategy:
      matrix:
        target:
          - x86_64-pc-windows-msvc
          - x86_64-unknown-linux-gnu
          - aarch64-apple-darwin
          - x86_64-apple-darwin
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            ext: .exe
          - target: aarch64-apple-darwin
            os: macos-latest
          - target: x86_64-apple-darwin
            os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - run: cargo build --verbose --release --bin wasm2spirv --all-features --target ${{ matrix.target }}
      - uses: Shopify/upload-to-release@v1.0.1
        with:
          name: wasm2spirv-${{ matrix.target }}${{ matrix.ext }}
          path: target/${{ matrix.target }}/release/wasm2spirv${{ matrix.ext }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
