name: Release

on:
  release:
    types: [published]

jobs:
  build-cli:
    permissions:
      contents: write

    strategy:
      matrix:
        target:
          - x86_64-pc-windows-msvc
          - x86_64-unknown-linux-gnu
          - aarch64-apple-darwin
          - x86_64-apple-darwin
          - wasm32-wasi
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            features: khronos-all naga-wgsl
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            features: khronos-all naga-wgsl
            ext: .exe
          - target: aarch64-apple-darwin
            os: macos-latest
            features: khronos-all naga-wgsl
          - target: x86_64-apple-darwin
            os: macos-latest
            features: khronos-all naga-wgsl
          - target: wasm32-wasi
            os: ubuntu-latest
            features: naga-all
            ext: .wasm

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Restore cache
        uses: actions/cache/restore@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ matrix.target }}-cargo-${{ runner.os }}-release-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ matrix.target }}-cargo-${{ runner.os }}-release
            ${{ matrix.target }}-cargo-${{ runner.os }}-
            ${{ matrix.target }}-cargo-

      - run: rustup target add ${{ matrix.target }}
      - run: cargo build --verbose --release --bin wasm2spirv --features="cli ${{ matrix.features }}" --target ${{ matrix.target }}

      - name: Save cache
        uses: actions/cache/save@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ matrix.target }}-cargo-${{ runner.os }}-release-${{ hashFiles('**/Cargo.lock') }}

      - name: Upload to release
        uses: svenstaro/upload-release-action@2.6.1
        with:
          file: target/${{ matrix.target }}/release/wasm2spirv${{ matrix.ext }}
          asset_name: wasm2spirv-${{ matrix.target }}${{ matrix.ext }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
