name: Release

on:
  release:
    types: [prereleased, released]

jobs:
  build-cli:
    strategy:
      matrix:
        os: [ubuntu-latest]
        target: [x86_64-pc-windows-msvc, x86_64-unknown-linux-gnu, aarch64-apple-darwin, x86_64-apple-darwin]
        exclude:
          - target: x86_64-pc-windows-msvc
            os: ubuntu-latest
        include:
          - target: x86_64-pc-windows-msvc
            os: windows-latest

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - run: cargo build --verbose --release --bin wasm2spirv --features="clap color-eyre serde_json spirv-tools spirv_cross" --target ${{ matrix.target }}

  publish-to-crates-io:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo publish --verbose
