name: Release

on:
  release:
    types: [published]

jobs:
  build-cli:
    strategy:
      matrix:
        target:
          - x86_64-pc-windows-msvc
          - x86_64-unknown-linux-gnu
          - aarch64-apple-darwin
          - x86_64-apple-darwin
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            ext: .exe
          - target: aarch64-apple-darwin
            os: macos-latest
          - target: x86_64-apple-darwin
            os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ matrix.target }}-cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ matrix.target }}-cargo-${{ runner.os }}-
            ${{ matrix.target }}-cargo-

      - uses: actions/checkout@v3
      - run: rustup target add ${{ matrix.target }}
      - run: cargo build --verbose --release --bin wasm2spirv --all-features --target ${{ matrix.target }}

      - name: Upload to release
        uses: svenstaro/upload-release-action@2.6.1
        with:
          file: target/${{ matrix.target }}/release/wasm2spirv${{ matrix.ext }}
          asset_name: ${{ matrix.target }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
