name: Tests

on: push

jobs:
  test-examples:
    strategy:
      matrix:
        example:
          - dot
          - saxpy
          - square
          - fragment
          - min

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Restore cache
      uses: actions/cache@v3
      with:
        path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
        key: cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
            cargo-

    - run: cargo run --bin wasm2spirv --features="cli spvt-validate" -- examples/${{ matrix.example }}/${{ matrix.example }}.wat --from-json examples/${{ matrix.example }}/${{ matrix.example }}.json --validate
